### ISSUE TITLE
static compilation warning

### ISSUE THREAD

**Issue by leogr** [codenotary/cas#58]
```
$ go build -a -tags netgo -ldflags '-s -X github.com/vchain-us/vcn/pkg/meta.version=v0.7.0 -extldflags "-static"' ./cmd/vcn
# github.com/vchain-us/vcn/cmd/vcn
/usr/bin/ld: /tmp/go-link-596993440/000006.o: in function `mygetgrouplist':
/usr/lib/go/src/os/user/getgrouplist_unix.go:16: warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-596993440/000005.o: in function `mygetgrgid_r':
/usr/lib/go/src/os/user/cgo_lookup_unix.go:38: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-596993440/000005.o: in function `mygetgrnam_r':
/usr/lib/go/src/os/user/cgo_lookup_unix.go:43: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-596993440/000005.o: in function `mygetpwnam_r':
/usr/lib/go/src/os/user/cgo_lookup_unix.go:33: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-596993440/000005.o: in function `mygetpwuid_r':
/usr/lib/go/src/os/user/cgo_lookup_unix.go:28: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

```
$ go mod why os/user
# os/user
github.com/vchain-us/vcn/pkg/extractor/dir
gopkg.in/src-d/go-git.v4/plumbing/format/gitignore
os/user
```

**Comment by ivan-w** [comment]
When I have a second, I will look into this. Chances are it's perfectly innocuous

**Comment by ivan-w** [comment]
However I hate to see those kind of warnings. There is also a possibility it is actually a golang issue. It's as if some of the golang->C bindings libraries are not being properly linked. Another issue could be hte use of TLS (Thread Local Storage) with those functions ending in "_r" but I can't remember any restictions on using TLS with static executables.

**Comment by leogr** [comment]
Not sure, but I believe it depends on how `glibc` is implemented, so golang can do nothing to avoid that.
Anyhow, afaik, it could be a problem if the static executable is using those functions (vcn should not, but I cannot be sure because 3rd-party dependencies).

How can we double check this?

**Comment by ivan-w** [comment]
Ok. I's indeed an issue with glibc (I can reproduce with a 10 lines C program) and I think I know what the problem is (it's not a bug, it's a feature !)
```
ivan@db08:~/tst2$ cat foobar.c
#include <sys/types.h>
#include <pwd.h>
#include <stdio.h>
#include <stdlib.h>
int main(int ac,char **av)
{
    struct passwd *p;
    p=getpwuid(0);
    printf("%s\n",p->pw_name);
    return 0;
}

ivan@db08:~/tst2$ gcc foobar.c -o foobar
ivan@db08:~/tst2$ ./foobar
root
ivan@db08:~/tst2$ gcc -static foobar.c -o foobar
/usr/bin/ld: /tmp/ccxIZlnS.o: in function `main':
foobar.c:(.text+0x15): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
ivan@db08:~/tst2$ ./foobar
root
ivan@db08:~/tst2$

```
So why the warning you may wonder ?

Of all the C functions in glibc, a few use some loadable plugins that are loaded at runtime and depend on the configuration. For example, getpwuid() rely on /etc/nsswitch.conf and depending on the contents, glibc will issue dlopen() to load the appropriate module(s).
Unfortunately, dlopen() can only be issued from a dynamic executable - or at least that used to be the case.

And even if you can use dlopen(), the shared modules loaded will have to be present and themselves will trigger loading of the shared C library (so it won't be a standalone executable).

In those cases, the module contains a note section and the linker/binder will emit the message we see and those routines will resort to using the embedded compatible version.

It won't crash though (tried running it in a scratch docker image and worked as expected)
